server:
  port: 8086
hm:
  db:
    database: hm-trade
feign:
  okhttp:
    enabled: true # 启用 OKHttp
spring:
  cloud:
    sentinel:
      transport:
        dashboard: localhost:8090  # Sentinel 控制台地址
      http-method-specify: true     # 是否将 HTTP 方法作为资源名一部分

# keytool -genkeypair -alias hmall -keyalg RSA -keypass hmall123 -keystore hmall.jks -storepass hmall123