server:
  port: 8086
hm:
  db:
    database: hm-trade
feign:
  okhttp:
    enabled: true # 启用 OKHttp
# keytool -genkeypair -alias hmall -keyalg RSA -keypass hmall123 -keystore hmall.jks -storepass hmall123